apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv1
  namespace: jenkins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: jenkins.unixcloudfusion.in
    path: "/data"
